import type { Metadata } from "next";
import "./globals.css";
import CartProvider from "./context/CartContext";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
          <div className="min-h-screen min-w-screen flex items-center justify-center">
            <div className="min-w-screen text-center">
                <CartProvider>
                  <Header />
                    {children}
                  <Footer />
                </CartProvider>
            </div>
          </div>
      </body>
    </html>
  );
}
